package uk.org.fancy.nxapi.mobile;
import android.app.Activity; import android.content.Intent; import android.graphics.Color; import android.net.Uri; import android.os.Bundle; import android.os.Handler; import android.webkit.*; import android.widget.*; import com.discord.socialsdk.DiscordSocialSdkInit;
import java.io.*; import java.net.*; import java.util.zip.*;

public class MainActivity extends Activity {
    private static final String DEFAULT_OAUTH_CLIENT_ID="W7bZ6IqKORfU0w9fe_M2mQ";
    private static boolean nodeStarted; private static String nodeAccessKey; private static String nodeNonce; private static int nodePort; private WebView webView; private String pendingRedirect; private String accessKey; private String nonce; private int port; private boolean discordStarted; public static final long DISCORD_APPLICATION_ID=1552978394914754592L;
    static { System.loadLibrary("node"); System.loadLibrary("nxapi-node"); }
    public native int startNodeWithArguments(String[] arguments);
    public static native int startDiscordPresence(long applicationId);
    public static native void updateDiscordPresence(String gameName,String imageUrl,String details,String state,long startedAt);
    public static native int getDiscordPresenceStatus();
    public static native void stopDiscordPresence();
    @Override public void onCreate(Bundle state){super.onCreate(state);handleIntent(getIntent());String clientId=getPreferences(MODE_PRIVATE).getString("oauth_client_id",DEFAULT_OAUTH_CLIENT_ID);if(clientId.isEmpty())showClientSetup();else beginStartup(clientId);}
    private void showClientSetup(){final EditText input=new EditText(this);input.setHint("OAuth client ID");input.setPadding(48,16,48,16);new android.app.AlertDialog.Builder(this).setTitle("Coral認証の準備").setMessage("nxapi-authでPublicクライアントを作成し、表示されたClient IDを貼り付けてください。Scopeはca:gf ca:er ca:drを有効にしてください。").setView(input).setNeutralButton("登録ページ",(d,w)->{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://nxapi-auth.fancy.org.uk/oauth/clients")));showClientSetup();}).setPositiveButton("保存",(d,w)->{String id=input.getText().toString().trim();if(id.isEmpty()){showClientSetup();return;}getPreferences(MODE_PRIVATE).edit().putString("oauth_client_id",id).apply();beginStartup(id);}).setCancelable(false).show();}
    private void beginStartup(String clientId){synchronized(MainActivity.class){if(nodeStarted){accessKey=nodeAccessKey;nonce=nodeNonce;port=nodePort;}else{java.security.SecureRandom random=new java.security.SecureRandom();accessKey=new java.math.BigInteger(130,random).toString(32);nonce=new java.math.BigInteger(130,random).toString(32);port=20000+random.nextInt(20000);nodeAccessKey=accessKey;nodeNonce=nonce;nodePort=port;}}showLoading("nxapiを起動しています…");new Thread(()->{try{File project=extractNodeProject();ensureNodeStarted(project,clientId);waitForServer();runOnUiThread(this::configureWebView);}catch(Exception e){runOnUiThread(()->showFatal(e));}},"nxapi-setup").start();}
    private String appUrl(){return "http://127.0.0.1:"+port+"/?key="+accessKey+"&standalone=1&v="+BuildConfig.VERSION_CODE;}
    private void ensureNodeStarted(File project,String clientId){synchronized(MainActivity.class){if(nodeStarted)return;nodeStarted=true;new Thread(()->startNodeWithArguments(new String[]{"node",new File(project,"main.mjs").getAbsolutePath(),getFilesDir().getAbsolutePath(),accessKey,Integer.toString(port),nonce,clientId}),"nxapi-node").start();}}
    private synchronized File extractNodeProject() throws Exception {File target=new File(getFilesDir(),"nodejs-project-v"+BuildConfig.VERSION_CODE),ready=new File(target,".ready");if(ready.exists())return target;if(!target.exists()&&!target.mkdirs())throw new Exception("実行フォルダーを作成できません");String root=target.getCanonicalPath()+File.separator;try(InputStream input=getAssets().open("node-project.zip");ZipInputStream zip=new ZipInputStream(input)){ZipEntry entry;byte[] buffer=new byte[65536];while((entry=zip.getNextEntry())!=null){File output=new File(target,entry.getName());if(!output.getCanonicalPath().startsWith(root))throw new SecurityException("Invalid asset path");if(entry.isDirectory()){output.mkdirs();continue;}File parent=output.getParentFile();if(parent!=null)parent.mkdirs();try(FileOutputStream stream=new FileOutputStream(output)){int read;while((read=zip.read(buffer))>0)stream.write(buffer,0,read);}}}if(!ready.createNewFile())throw new Exception("展開を完了できません");return target;}
    private void waitForServer() throws Exception {Exception last=null;for(int i=0;i<240;i++){try{HttpURLConnection c=(HttpURLConnection)new URL("http://127.0.0.1:"+port+"/health").openConnection();c.setConnectTimeout(500);c.setReadTimeout(500);if(c.getResponseCode()==200){try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()))){String body=r.readLine();if(body!=null&&body.contains("\"nonce\":\""+nonce+"\"")){c.disconnect();return;}}}}catch(Exception e){last=e;}Thread.sleep(250);}throw new Exception("内蔵nxapiサーバーを起動できません",last);}
    private void configureWebView(){webView=new WebView(this);webView.setBackgroundColor(Color.rgb(13,15,20));WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setUserAgentString(s.getUserAgentString()+" nxapi-standalone-android/1.0");android.webkit.CookieManager.getInstance().setAcceptCookie(true);android.webkit.CookieManager.getInstance().setAcceptThirdPartyCookies(webView,false);webView.setWebChromeClient(new WebChromeClient());webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return route(r.getUrl());}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return route(Uri.parse(u));}@Override public void onPageFinished(WebView v,String u){if(pendingRedirect!=null&&u.startsWith("http://127.0.0.1:"+port+"/")){String value=pendingRedirect;pendingRedirect=null;v.evaluateJavascript("(()=>{const i=document.querySelector('#redirectUrl');if(i){i.value="+jsString(value)+";document.querySelector('#completeLogin').click()}})()",null);}}});webView.addJavascriptInterface(new DiscordBridge(),"AndroidDiscord");setContentView(webView);webView.loadUrl(appUrl());}
    private boolean route(Uri uri){if(uri!=null&&"npf71b963c1b7b6d119".equals(uri.getScheme())){pendingRedirect=uri.toString();webView.loadUrl(appUrl());return true;}return false;}
    private void handleIntent(Intent i){Uri d=i==null?null:i.getData();if(d!=null&&"npf71b963c1b7b6d119".equals(d.getScheme()))pendingRedirect=d.toString();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);handleIntent(i);if(webView!=null)webView.loadUrl(appUrl());}
    @Override public void onBackPressed(){if(webView!=null&&webView.canGoBack())webView.goBack();else super.onBackPressed();}
    private final class DiscordBridge { @JavascriptInterface public void connect(){runOnUiThread(()->{String url=webView==null?null:webView.getUrl();if(url!=null&&url.startsWith("http://127.0.0.1:"+port+"/"))startDiscordRpc();});} @JavascriptInterface public void disconnect(){runOnUiThread(()->{stopService(new Intent(MainActivity.this,DiscordPresenceService.class));stopDiscordPresence();discordStarted=false;Toast.makeText(MainActivity.this,"Discord連携を停止しました",Toast.LENGTH_SHORT).show();});} }
    private void startDiscordRpc(){try{if(discordStarted){Toast.makeText(this,"Discord連携は開始済みです",Toast.LENGTH_SHORT).show();return;}Intent rpcService=new Intent("com.discord.socialsdk.rpc.IDiscordRpcService").setPackage("com.discord");if(getPackageManager().resolveService(rpcService,0)==null){Toast.makeText(this,"Discordを最新版に更新して起動してください",Toast.LENGTH_LONG).show();return;}if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},2774);DiscordSocialSdkInit.setEngineActivity(this);Intent service=new Intent(this,DiscordPresenceService.class).putExtra("endpoint","http://127.0.0.1:"+port).putExtra("accessKey",accessKey);startForegroundService(service);discordStarted=true;Toast.makeText(this,"ゲーム情報をDiscordへ接続中…",Toast.LENGTH_SHORT).show();showDiscordStatus(0);}catch(Throwable e){discordStarted=false;Toast.makeText(this,"Discord連携に失敗しました: "+e.getClass().getSimpleName(),Toast.LENGTH_LONG).show();}}
    private void showDiscordStatus(int attempt){new Handler(getMainLooper()).postDelayed(()->{if(!discordStarted)return;int status=getDiscordPresenceStatus();if(status==2){Toast.makeText(this,"ゲーム情報のDiscord連携を開始しました",Toast.LENGTH_LONG).show();}else if(status<0){stopService(new Intent(this,DiscordPresenceService.class));discordStarted=false;Toast.makeText(this,"DiscordがRPC連携を拒否しました",Toast.LENGTH_LONG).show();}else if(attempt<20){showDiscordStatus(attempt+1);}else{stopService(new Intent(this,DiscordPresenceService.class));discordStarted=false;Toast.makeText(this,"Discord接続がタイムアウトしました",Toast.LENGTH_LONG).show();}},500);}
    @Override protected void onDestroy(){super.onDestroy();}
    private void showLoading(String m){TextView t=new TextView(this);t.setText(m);t.setTextColor(Color.WHITE);t.setTextSize(18);t.setGravity(17);t.setBackgroundColor(Color.rgb(13,15,20));setContentView(t);}
    private void showFatal(Exception e){showLoading("起動に失敗しました\n\n"+e.getMessage());Toast.makeText(this,e.toString(),Toast.LENGTH_LONG).show();}
    private static String jsString(String v){return "\""+v.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
}
