cmake_minimum_required(VERSION 3.22.1)
project(nxapi_mobile)
include_directories(libnode/include/node)
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libnode/bin/${ANDROID_ABI}/libnode.so)
find_package(discord_partner_sdk REQUIRED CONFIG)
add_library(nxapi-node SHARED src/main/cpp/node-start.cpp src/main/cpp/discord-presence.cpp)
find_library(log-lib log)
target_link_libraries(nxapi-node node discord_partner_sdk::discord_partner_sdk ${log-lib})
